name: Shared DeepSeek Review

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run DeepSeek Review
        uses: hustcer/deepseek-review@v1
        env:
          CHAT_TOKEN: ${{ secrets.TOKEN }}
        with:
          temperature: 0.3